//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X2J.Core.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X2J.Core.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;Annotation&quot;
        ///    targetNamespace=&quot;http://tempuri.org/Annotation.xsd&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns=&quot;http://tempuri.org/Annotation.xsd&quot;
        ///    xmlns:mstns=&quot;http://tempuri.org/Annotation.xsd&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:element name=&quot;Dummy&quot;&gt;
        ///    &lt;xs:annotation&gt;
        ///      &lt;xs:documentation&gt;Sample Documentation&lt;/xs:documentation&gt;
        ///      &lt;xs:appinfo&gt;Sample Annotation&lt;/xs:appinfo&gt;
        ///    &lt;/xs:annotation&gt;
        ///  &lt;/xs:eleme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Annotation {
            get {
                return ResourceManager.GetString("Annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///  &lt;xsd:element name=&quot;mails&quot; type=&quot;mailsType&quot; /&gt;
        ///
        ///  &lt;xsd:complexType name=&quot;mailsType&quot;&gt;
        ///    &lt;xsd:sequence minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///      &lt;xsd:element name=&quot;mail&quot; type=&quot;mailType&quot; /&gt;
        ///    &lt;/xsd:sequence&gt;
        ///  &lt;/xsd:complexType&gt;
        ///
        ///  &lt;xsd:complexType name=&quot;mailType&quot;&gt;
        ///    &lt;xsd:sequence&gt;
        ///      &lt;xsd:element name=&quot;envelope&quot; type=&quot;envelopeType&quot; /&gt;
        ///      &lt;xsd:element name=&quot;body&quot; type=&quot;bodyType&quot; /&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mails {
            get {
                return ResourceManager.GetString("Mails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///          xmlns:tns=&quot;http://tempuri.org/PurchaseOrderSchema.xsd&quot; 
        ///          targetNamespace=&quot;http://tempuri.org/PurchaseOrderSchema.xsd&quot; 
        ///          elementFormDefault=&quot;qualified&quot;&gt;
        ///  &lt;xsd:element name=&apos;comment&apos; type=&apos;xsd:string&apos;/&gt;
        ///
        ///  &lt;xsd:element name=&apos;purchaseOrder&apos; type=&apos;tns:PurchaseOrderType&apos;/&gt;
        ///
        ///  &lt;xsd:complexType name=&apos;USAddress&apos;&gt;
        ///    &lt;xsd:annotation&gt;
        ///      &lt;xsd:documentation&gt;
        ///        Purchase order schema for Example.Microsoft.com.
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductSchema {
            get {
                return ResourceManager.GetString("ProductSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///  &lt;xs:element name=&quot;pet&quot; type=&quot;PetType&quot;/&gt;
        ///  
        ///  &lt;xs:attributeGroup name=&quot;NameAgeAttributes&quot;&gt;
        ///    &lt;xs:attribute name=&quot;age&quot; type=&quot;xs:integer&quot; use=&quot;required&quot;/&gt;
        ///    &lt;xs:attribute name=&quot;name&quot; type=&quot;xs:string&quot; use=&quot;required&quot;/&gt;
        ///  &lt;/xs:attributeGroup&gt;
        ///
        ///  &lt;xs:complexType name=&quot;PetType&quot;&gt;
        ///    &lt;xs:attributeGroup ref=&quot;NameAgeAttributes&quot;/&gt;
        ///  &lt;/xs:complexType&gt;
        ///
        ///  &lt;xs:element name=&quot;cat&quot; substitutionGroup=&quot;pet&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:complexCont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Relationships {
            get {
                return ResourceManager.GetString("Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://dyomedea.com/ns/library&quot;
        ///  elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;
        ///  xmlns:lib=&quot;http://dyomedea.com/ns/library&quot;
        ///  xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;book&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;title&quot; type=&quot;xs:token&quot;/&gt;
        ///        &lt;xs:element name=&quot;author&quot; type=&quot;xs:token&quot;
        ///          maxOccurs=&quot;unbounded&quot;/&gt;
        ///        &lt;xs:any namespace=&quot;##other&quot; processContents=&quot;lax [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleSampleSchema {
            get {
                return ResourceManager.GetString("SimpleSampleSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///           xmlns:tns=&quot;http://tempuri.org/PurchaseOrderSchema.xsd&quot; 
        ///           targetNamespace=&quot;http://tempuri.org/PurchaseOrderSchema.xsd&quot; 
        ///           elementFormDefault=&quot;qualified&quot;&gt;
        /// &lt;xsd:element name=&quot;PurchaseOrder&quot; type=&quot;tns:PurchaseOrderType&quot;/&gt;
        /// &lt;xsd:complexType name=&quot;PurchaseOrderType&quot;&gt;
        ///  &lt;xsd:sequence&gt;
        ///   &lt;xsd:element name=&quot;ShipTo&quot; type=&quot;tns:USAddress&quot; maxOccurs=&quot;2&quot;/&gt;
        ///   &lt;xsd:element name=&quot;BillTo&quot; type=&quot;tns:USAddress&quot;/&gt;
        ///  &lt;/xsd:sequenc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleSchema {
            get {
                return ResourceManager.GetString("SimpleSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns:pg=&quot;http://tempuri.org/PriceSchema.xsd&quot;
        ///           targetNamespace=&quot;http://tempuri.org/PriceSchema.xsd&quot;
        ///           elementFormDefault=&quot;qualified&quot;&gt;
        ///&lt;xsd:group name=&quot;priceGroup&quot;&gt;
        ///  
        ///  &lt;xsd:annotation&gt;
        ///    &lt;xsd:documentation xml:lang=&quot;en&quot;&gt;
        ///      A price is any one of the following:
        ///      * Full Price (with amount)
        ///      * Sale Price (with amount and authorization)
        ///      * Clearance Price (with amount and authorization)
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLSchemaGroupSample {
            get {
                return ResourceManager.GetString("XMLSchemaGroupSample", resourceCulture);
            }
        }
    }
}
